import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles({
    root: {
        maxWidth: 320,
        margin: "0.2rem",   
    },
    category: {
        display: "flex",
        backgroundColor: "#FF0000", 
        color: "#FFF0F0",
        width: "-webkit-max-content",
        height: "2rem",
        fontWeight: "bolder",
        justifyContent: "center",
        paddingLeft: "1rem",
        paddingRight: "1rem",
        marginTop:"-2rem",
        alignItems: "center",
    },
    dt: {
        display:"flex",
        flexDirection:"column",
        backgroundColor: "#FF0000!important",
        color: "#FFF0F0",
        width: "-webkit-max-content",
        height: "3rem",
        paddingLeft: "0.5rem",
        paddingRight: "0.5rem",
        marginTop:"0.5rem",
        textAlign:"center",
        fontSize: "0.7rem",
        fontWeight: "bolder",
        justifyContent: "center",
        alignItems: "center",
        borderRadius: "100%",
        margin: "auto",
        marginRight: "0.3rem",
    },
    image:{
        height: "15rem",
        backgroundSize: '100%',
        marginTop: "-3.5rem",
    },
    imgContainer:{
        display: "flexGrow",
    },
    description: {
        height: 65,
        display: '-webkit-box',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
    },
    icon:{
        color:'#FF0000', 
        justifyContent: "flex-start", 
        marginBottom:"1rem", 
        marginTop:"1rem",
    },
    tags:{
        color:'#FF0000', 
        justifyContent: "flex-start",  
        alignSelf: "center",
        fontWeight: "bolder",
    },
    actions:{
        justifyContent: "flex-end", 
        marginTop: "5rem", 
        alignItems: "flex-end",
    },
    button:{
        backgroundColor: "#FF0000", 
        color: "#FFF0F0", 
        marginTop: "7rem",
        paddingLeft: "1.5rem",
        paddingRight: "1.5rem",
        fontWeight: "bolder",
    },
});